### ISSUE TITLE
Question: triggering signals from within signal handlers?

### ISSUE THREAD

**Issue by StevenLangbroek** [christianalfoni/cerebral#22]
I'm experimenting with cerebral, and have a maybe quite weird use-case. I'm writing a validator for an external data-format parts of our system consume (VAST), and have sort of the following flow in mind:

- Choose "From URL" or "From XML" (as in: input raw XML)
- Choose whether to proxy or not
- Enter either URL or XML (in Codemirror)
- Click "Start Validation"
- Fetch remote URL or take XML from input

At this point it gets a bit murky for me. The response (a quite deeply nested object with arrays 'n such) needs to go through the code we use for processing in our client. The function basically behaves like so:

```js
this.VASTClient.get(url, (response) => {
  // traverse the response object with all sorts of ugly loops. not my code :/
});
```

What I want to do, is if we get a valid response, walk through this logic, but instead of taking the actions our normal client would take, push signals onto cerebral (`cerebral.signals.logMessagePushed(node)`). Can I just call `cerebral.signals.[signalName]` from another signal handler? What's your advice here?

My idea was (slight pseudocode):

```js
cerebral.signal('onValidationStarted', getVast, setVast, traverseResponse);
```

where traverseResponse behaves sort of like:

```js
export default function traverseResponse(cerebral, vastResponse){
   vastResponse.ads.forEach((ad) => {
       cerebral.signals.messageLogged('Entered adNode', ad);
   });
};
```

**Comment by christianalfoni** [comment]
Hi @StevenLangbroek ,

I like to repeat stuff with my own words just to make sure I understand it. So here goes :-)

You want to trigger a signal that runs the validation. The validation process is to query the server and get a response which needs to be traversed by "traverseResponse"?

If so I would continue using actions a long your signal. It might feel a bit weird at first, but signals with many actions is a good thing, rather than having one signal triggering an other. The reason is that a signal with many actions is easier to read than one signal triggering an other signal triggering an other signal. Your code will still be dry because you can quite easily reuse actions across signals. Okay, enough abstract thoughts here. So either:

```js
export default function traverseResponse(cerebral, vastResponse){
   vastResponse.ads.forEach((ad) => {
       cerebral.push('logs', ad); // You just want to add them to a log?
   });
};
```
Or: 

```js
cerebral.signal('onValidationStarted', getVast, setVast, logMessages);
cerebral.signal('messageLogged', logMessages);
```

**Comment by christianalfoni** [comment]
Hi @StevenLangbroek ,

I like to repeat stuff with my own words just to make sure I understand it. So here goes :-)

You want to trigger a signal that runs the validation. The validation process is to query the server and get a response which needs to be traversed by "traverseResponse"?

If so I would continue using actions a long your signal. It might feel a bit weird at first, but signals with many actions is a good thing, rather than having one signal triggering an other. The reason is that a signal with many actions is easier to read than one signal triggering an other signal triggering an other signal. Your code will still be dry because you can quite easily reuse actions across signals. Okay, enough abstract thoughts here. So either:

```js
export default function traverseResponse(cerebral, vastResponse){
   vastResponse.ads.forEach((ad) => {
       cerebral.push('logs', ad); // You just want to add them to a log?
   });
};
```
Or: 

```js
export default function traverseResponse(cerebral, vastResponse){
   return vastResponse.ads.map((ad) => {
     return ad;
   });
};
```

```js
cerebral.signal('onValidationStarted', getVast, setVast, traverseResponse, logMessages);
cerebral.signal('messageLogged', logMessages);
```

```js
export default function logMessages(cerebral, messages){
  if (Array.isArray(messages) {
   cerebral.concat('logs', messages);
  } else {
    cerebral.push('logs', messages);
  }
};
```

Does this make sense? :-)

**Comment by StevenLangbroek** [comment]
Yup, I was overthinking it.
