### ISSUE TITLE
Handle XHR / Promise rejection

### ISSUE THREAD

**Issue by StevenLangbroek** [christianalfoni/cerebral#24]
How do I handle promise rejection / XHR errors in Cerebral? Can't find much info about this.. Any guidance would be appreciated :).

**Comment by christianalfoni** [comment]
Hi @StevenLangbroek ,

Yeah, documentation is still lacking a bit. It will be a lot better as soon as the first "production" application of Cerebral is out :-)

Currently you handle rejections like resolved values. So typically you might build a result object that will be passed to the next action:

```js
cerebral.signal('somethingHappened', function ActionA () {
  return new Promise(function (resolve, reject) {
    if (someCondition) {
      resolve({ok: true});
    } else {
      reject({ok: false});
    }
  });
}, function ActionB (cererbral, result) {
  if (result.ok) {

  } else {

  }
});
```
If this is not working, there is a bug ;-)

**Comment by StevenLangbroek** [comment]
So it always moves on to the next action, regardless or Promise result? Would be nice to have some sort of mechanism that takes care of this...

**Comment by christianalfoni** [comment]
I updated the issue, make sure you read the last version :-)

It only moves to next action on "resolve". "Resolve" means... I want to handle this. A reject stops the promise and next action will not run. But this should be due to en exception. An ajax error result should be handled and therefor should be a resolved promise. At least in my opinion :-)

**Comment by christianalfoni** [comment]
Latest version of Cerebral has a path implementation for promises :-)
