### ISSUE TITLE
New Feature: "Conditionals"

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/cerebral#43]
It is suggested that the signal chain needs the ability to conditionally run actions. The current suggestion is to move even closer to traditional middleware where you have a "next" resolver. We also introduce the use of `{}` arbitrarily to allow paths to be resolved.

```js
const SUCCESS = 'SUCCESS';
const ERROR = 'ERROR';

// We introduce a "next" resolver instead. It is to be used to resolve values 
// to the args object and/or choose path

const syncOrAsyncAction = function (args, state, next) {
  if (condition) {
    next(SUCCESS, {foo: 'bar'});
  } else {
    next(ERROR, {foo: 'bar'});
  }
}

// With Babel and ES6 syntax this can be expressed like this

controller.signal('appMounted', syncOrAsyncAction, {
  [SUCCESS]: [],
  [ERROR]: []
});

controller.signal('appMounted', [syncOrAsyncAction, {
  [SUCCESS]: [],
  [ERROR]: []
}]);
```

So the questions here are:

1. What should happen when you resolve `next({})`, but there is a path to go down. Should it throw error? Should it go down the first path? Or a DEFAULT key path?

2. What about the opposite? You want to go down a path, but it does not exist? Should probably be error? 

3. Is it required to use `next()`with sync actions? Or should it just move on? Or should the signal stop?

In regards of migration we can still allow returning values and use "resolve/reject" methods, just warn DEPRECATION.

**Comment by christianalfoni** [comment]
I am currently thinking:

1. We should throw error, as there is a reason why you want to have multiple paths
2. We should throw error
3. I think we should throw error if `next()` is not called, if you want to stop an action I think you should explicitly state that with:

```js
const action = function (args, state, next) {
  if (conditional) {
    next(SUCCESS, {foo: 'bar'});
  } else {
    next(STOP);
  }
};
controller.signal('appMounted', action, {
  [SUCCESS]: [doSomethingMore],
  [STOP]: []
});
```
This way you can read both in the action and the signal where something can/will stop.

**Comment by garth** [comment]
This is looking pretty robust to me.

**Comment by a-s-o** [comment]
Hi Christian,

After our discussion in #45, I read this again. Have you locked down this api? I have some concern about coupling the action creation and signal creation in this way. Any actions defined this way will need to be aware of the possible exit points and the signal creation.

Are you still considering other ideas here? I don't really have a solution in mind but I can give it some thought.

**Comment by christianalfoni** [comment]
Hi again,

Nopes, not locked it yet.

Please bring on your thoughts on this. I will wait :-)

You bring up a valid concern. The initial Cerebral version had no action/signal coupling at all. Then the args argument was introduced to share values across actions, which does create a contract between actions. This implementation would create a contract between the actions and the signals.

The most important thing is readability I think. And now you see clearly what paths an action can take. It does reduce the actions reusability, but again... paths are not a common thing, except for async stuff, which already has paths. 

But yeah, lets put this cake on ice for a little bit, just to make sure we are doing the right thing :-)

**Comment by a-s-o** [comment]
Hi, thanks for your consideration. 

I see major benefit of having actions separate from signals is re-use. I am dealing with the args coupling by validating inputs and outputs, which is a little hard but doable. I find it useful, however, so I think it is worth it. 

How about we standardize

**Comment by a-s-o** [comment]
Whoops, incomplete comment there. I was going to suggest looking at two different ideas:

1) Multi path approach but action definition should be changed to make it more declarative
See example at http://node-machine.org/spec/machine 

In this way the actions themselves decide the possible output paths. Then the signals can choose to use or not use certain paths. Like you said this is great for readability and understanding. 

This also allows global optimization by memoizing certain actions, etc. Again, as I said, a very useful approach but harder to use initially, and more documentation.  Signals can also analyze when unexpected output paths are used.

I think if you would like to take the multi path approach, this is a must, so that even if there is a coupling, it is at least somewhat expected and maintainable.

I would prefer this since I this can be very useful for catching errors during development.

2) Standardize on a single output interface. I do like the existing resolve/reject; maybe throw a catch option in there to handle thrown exceptions and I think it will handle a lot of cases. Or vent node style callbacks (err, result).

This is much easier to use, document and maintain in the library.

Again, I prefer option 1 but you may or may not want that in the library. I will let you decide. If you need implementation help, I can definately help with that.

Thanks

**Comment by christianalfoni** [comment]
Btw, I just want to point out that this is default behaviour:
```js
const action = function (args, state, next) {
  next();
};
controller.signal('appMounted', action, nextAction);
```
A path split is only introduced when you need conditionals, like HTTP callbacks or some special stuff.

Hm, I do not quite see why you have to predefine the possible outputs on the action itself? I understand it for the type checker wrapper, but not by default?

Thanks for taking the time to explain and reference :-)

**Comment by a-s-o** [comment]
So, I think the way node-machines does this is that all actions have `outputs.error()` path so all thrown/unhandled exceptions go there. Then with the combination of `sync=true` and `defaultOutput='success'` any actions that return syncronously will have the returned value send down those paths. So if cerebral was to implement something like this, we could still allow the default behaviour that you showed above.

The reason for having outputs defined before hand is to catch path mismatches at compile time instead of at runtime. Basically if an action is defined like this:
```javascript
const userLogin = {
    outputs: {
        authenticated: { is_authenticated: t.Bool },
        notFound: { message: t.Str  }
    },
    fn: function (args, state, output) {
        if (/* not found */) {
            output.notFound({ message: 'User was not found' });
            return;
        }

        output.authenticated({ is_authenticated: true });
    }
};
```
This can be used somewhere else as follows
```javascript
const someSignal = cerebral.signal('someActionUsed', [userLogin, {
    error: [handleException],   // All actions have error path, so this is fine

    success: [doSomethingElse]  // Success path does not exist 
                                // for userLogin so error
                                // will be thrown here
                                // letting the user know that:
                                // 
                                // 'success' is not a valid output path; 
                                // available  paths are ['authenticated','notFound', 'error']
}])
```
As you see this way, the paths used in the signal can be checked when they are 
used resulting in a compile time error to be fixed right away. 

Furthermore, in the action definition it is easy to see which output paths the action
is exposing, so if there is something that the action does not do anymore (for instance,
we want to supress user_not_found messages),  we can simply delete that path and
all signals that use that path will throw and error for us to fix.

**Comment by christianalfoni** [comment]
Aha, I see what you mean. So basically we could allow typed and untyped actions:

1. Just a function, no type checking
2. Action definition with type checking

We could integrate this with the suggested implementation, just use duck typing. on the actions. If it is a function, no type checking, if it is an object with a `fn` method (or whatever) it is a typed action.

Does that make sense? :-)

So:

```js
const normalAction = function (args, state, next) {
  next();
};

const typedActionToPaths = {
  outputs: {
    success: {message: Cerebral.types.Bool}
  },
  fn(args, state, next) {
    next('success', {message: true});
  }
};

const typedAction = {
  output: {
    message: Cerebral.types.Bool
  },
  fn(args, state, next) {
    next({message: true});
  }
};
```

**Comment by a-s-o** [comment]
Yup, exactly. The only thing different I suggest is that, instead of doing `next(PATH, VALUE)` where path can be anything and can lead to bugs. We continue using the `next.PATH(VALUE)` so that path is limited to what was previously declared or some understood default paths like `next.resolve()` or `next.reject()` or `next.error()`

so your normal untyped actions can just be:
```javascript
var normalAction = function (args, state) {
   return { some_arg: 'xyz' };
}

var normalAsync = function (args, state, next) {
    ... 
    // Let's just say resolve, reject and error are default paths
    if (err) next.error({ message: 'something' })
    next.resolve({ some_arg: 'xyz' });       
}
```

**Comment by christianalfoni** [comment]
Okay, cool, then we are on the same page :-)

Let me let this sink in. I will create a new issue and redefine the spec for this implementation. Just want some feedback from the other guys contributing with suggestions and have experience with Cerebral :-)

Thanks for contributing with this. Type checking and compile time errors are especially beneficial for teams, but keep the reduced syntax for common projects. Very good!

**Comment by a-s-o** [comment]
Great, I'll look forward to that. Thanks for your time and help.

**Comment by christianalfoni** [comment]
Okay, created a new issue at #46. Would be great with some feedback there too, just to make sure that everyone is on the same page here :-)
