### ISSUE TITLE
Creating custom state mutation hooks

### ISSUE THREAD

**Issue by pstoica** [christianalfoni/cerebral#57]
ImmutableJS has a ton of different data structures which I find pretty useful (Set, OrderedMap, etc). Each data structure has its own special methods.

Does the current Cerebral API support custom state mutators? It seems hardcoded right now: https://github.com/christianalfoni/cerebral/blob/5483fb634b70bdf8833bbda00c024462d7cfa9ef/src/createActionArgs.js#L34

I want to start making an adapter and I think this would be great to have. But I can totally understand if you don't want to fragment the API across packages (write once and keep things swappable?).

**Comment by pstoica** [comment]
Started a package with ImmutableJS here: https://github.com/pstoica/cerebral-react-immutable-js

If we could add an `update` hook that takes a path and a function, you can use ImmutableJS's `updateIn` to run any needed methods. Unfortunately that's not serializable. Maybe you could do: `state.update(path, operationName /* e.g. union in Set().union */, args);`.

**Comment by christianalfoni** [comment]
@pstoica Really cool that you are playing around with this! 

Yeah, my initial thought was to conform immutable-js to the Cerebral API. That said, I am leaning towards just creating custom "mutations methods" related to the model layer. It should be able to take the full power of the model layer.

So instead of:
```js
Controller({
  onSet: ...
  onPush: ...
});
```

You can do:
```js
Controller({
  mutations: {
    myMutation1: ...
  }
});
```

The challenge there though is that some mutations takes only a path (like pop and shift), some takes path value, and some just value (top level)... but hm... maybe Cerebral should not convert the arguments to path/value at all. Maybe Cerebral should just call the mutaiton methods and its up to the package implementation to handle those arguments correctly in regards of being paths, values etc..

So:

 You can do:
```js
Controller({
  mutations: {
    myMutation1: function () {
      var path = [];
      if (typeof arguments[0] === 'string') {
        path = [arguments[0]];
      }
    }
  }
});
```
Or maybe that package will force you to always use an array as path... it is up to the package. And mutation methods are always defined in the package documentation, not generically in Cerebral documentation.

This would also be a nice part of the thought of creating `view-packages` and `model-packages`. So `cerebral-react` with `cerebral-immutable-js`. Then the model package is the controller itself, but lets you "attach" a view layer to it.

Any thoughts?

**Comment by christianalfoni** [comment]
btw, to give some more food for thought here. How do you think an ideal set of mutations would be between Cerebral and Immutable-JS?

**Comment by christianalfoni** [comment]
Custom mutations are in now
