### ISSUE TITLE
TodoMVC Demo App: Inccorect text insert behavior

### ISSUE THREAD

**Issue by hainguyenthanh** [christianalfoni/cerebral#58]
Hi Christian,

I think there's a bug in your TodoMVC demo app.

Here are the steps to reproduce this bug.
1. Open a web browser and navigate to the TodoMVC app, http://www.christianalfoni.com/todomvc
2. In the text field, enter some text, for example: **my task**
3. Place the caret in the middle of the text entered above, e.g. after **my**
4. Type some more text, e.g. **new**
5. The new text will not be inserted correctly in the text box. Instead of the expected text **my new task**, I received **my ntaskew**

Any solution of how to fix this?

**Comment by christianalfoni** [comment]
Ah, yes, sorry... this is due to signals running with "requestAnimationFrame" by default. The signal triggered on input change should have a `true` argument as its first argument. That will force the signal to run synchronously.

So:

```js
onChange={(e) => this.props.signals.inputChanged(true, {value: e.target.value})}
```
I will fix this, so keeping the issue open

I am also considering alternatives on handling this, but for now you use a `true` argument for inputs/textareas

**Comment by christianalfoni** [comment]
Fixed now :-)
