### ISSUE TITLE
Next Release Features

### ISSUE THREAD

**Issue by christianalfoni** [christianalfoni/cerebral#75]
Hi everyone,

I thought I would summarize suggestions again and prepare a new release.

## 1. Event emitting
Thanks to @markuplab

I will implement event emitting at different points in signal execution. Currently the following events will be implemented:

- Signal start
- Signal end
- Async action
- Action start
- Action end

## 2. Production optimizations
Currently there are a few things happening inside Cerebral that does not need to be part of a production build. Like typechecking and analyzing signals.

## 3. Services
Thanks to @bfitch and @dominicglenn

Currently any injected "services" is part of the input. It is suggested that we create an argument for this instead. Injecting services, like ajax etc. is a really good idea in regards of testing. It keeps the function pure and you can easily mock out "external" dependencies when testing.

I suggest we put it as the last argument for two reasons:

- Does not break current API
- It is not very often you need services, most actions are state changes. If you need services you will most certainly make an output also

```js
function myAction (input, state, output, services) {

}
```

Cerebral is a not a framework. It wants to encourage you to "pick the parts you like". Choose the best ajax library, underscore/lodash etc. With the services concept it is easy to replace these as new libraries become available. Also the really great thing, as suggested by @dominicglenn, is that you can use ES6 syntax to clearly see what services are injected into the action,

```js
function myAction (input, state, output, {ajax,_}) {

}
```

## 4. Allow outputs paths to have no argument
Thanks to @idream3 

When defining outputs with types it should also be a possibility to define that the output does not necessarily pass a value. The questions is, how to indicate it?

```js
action.output = {
  foo: String,
  bar: undefined, // It really is undefined, so is kind of correct?
  hoho: null // Null is really a value, but also indicates no value
};
```
Need help on this one :-)

## 5. Debugger log out tree
Thanks to @markuplab

Add a link to log out the all state of the model in the debugger

## 6. Error handling
Thanks to @a-s-o

There are some errors that should give a better warning: https://github.com/christianalfoni/cerebral/wiki/Errors

## Summary
Okay, so these are quite small fixes really. Let me know what you think and I will get on it ASAP :-) Thanks for all the great feedback!

**Comment by dominicglenn** [comment]
Regarding point 2, most other frameworks seem to strip this out in production. Specifically many immutable libraries do not freeze objects for example in production.

I'm not sure on the performance impact that having it on or off would have, but I don't see why it should be on in production.

**Comment by christianalfoni** [comment]
Hi @dominicglenn, yeah you make a good point. I was thinking of being able to use the really nice error messages you get when a type is wrong. Maybe an HTTP call would return something it should not and you would be able to grab that, not just a general error... but again. It should not happen.

But okay, hm hm... its not problem to change it either way so lets go with the convention of turning it off :-)

**Comment by gcanti** [comment]
Regarding point 4, I'd say something along the lines of:

- PropTypes
- [tcomb](https://github.com/gcanti/tcomb)

For example with tcomb you'd write:

```js
var t = require('tcomb');

action.output = t.struct({
  foo: t.String,          // a required string
  bar: t.maybe(t.Number), // an optional number: null, undefined or a number
  hoho: t.maybe(t.String) // an optional string: null, undefined or a string
});
```

or with the current cerebral API for custom types (i.e. using predicates):

```js
var t = require('tcomb');

action.output = {
  foo: t.String.is,          // a required string
  bar: t.maybe(t.Number).is, // an optional number: null, undefined or a number
  hoho: t.maybe(t.String).is // an optional string: null, undefined or a string
};
```

**Comment by a-s-o** [comment]
Hi @gcanti, so previously I suggested incorporating tcomb in cerebral for the type-checking part in #43 but Christian was apprehensive, rightly so, about adding a dependency if it is not necessary. I am already using tcomb and really like the error messages, etc. and I think it would work really well in case of cerebral input/output type but I can relate to Christian's concern about the dependency.

Do you think there is a way to incorporate tcomb, so that it is only a dependency during development time and gets removed in minification. For example, cerebral could start releasing cerebral.min.js which will not include tcomb at all but in cerebral.js all the type-checking and error reporting would work. 

For example would something like this work:
```javascript
const t = require('cerebral').types;

action.output = {
  foo: t.String.is,          // a required string
  bar: t.maybe(t.Number).is, // an optional number: null, undefined or a number
  hoho: t.maybe(t.String).is // an optional string: null, undefined or a string
};
```

Then in production we just stub out the `cerebral.types`

**Comment by gcanti** [comment]
> but Christian was apprehensive, rightly so, about adding a dependency if it is not necessary

I agree with both of you @a-s-o @christianalfoni. tcomb is tiny (~3K gzipped) but I think that cerebral shouldn't push to its users a particular solution, even the current default one if you ask me https://github.com/christianalfoni/cerebral/blob/master/src/types.js 
Maybe it could be shipped as separate addon (I know it's super tiny but it's also incomplete at the moment).

The current API (using predicates) already allows a pluggable runtime type system.

> Do you think there is a way to incorporate tcomb, so that it is only a dependency during development time and gets removed in minification

If you are using tcomb in your project likely you are also using it in order to describe your domain model, check the types across your app, leverage its immutability helpers and so on... so you don't want to remove the dependency. 

What could be easily done right away (2. Production optimizations) is removing the type check of cerebral in production. Maybe wrapping this check:

https://github.com/christianalfoni/cerebral/blob/master/src/CreateSignalFactory.js#L68

with a `process.env.NODE_ENV !== 'production'` test?

**Comment by christianalfoni** [comment]
Hi guys!

I have been working on the new release now and have only documentation stuff left to do.

I am a big fan of "hooks" to let developers choose their preferred tools and type checking is highly opinionated. But type checking is also important, so I want to make it supereasy to start getting into type checking. As you say @gcanti it will quickly come short, but then the goal is achieved. Maybe some developers not caring about type checking actually tried it because it was so easy to do and will level up as needed :-) But I will change documentation to highlight this part. The default type checking is there if you are not familiar with type checking, and make the "type hook" the preferred implementation.

Production optimizations now skips signal analysis for outputs and type checking on inputs and outputs.

And of course services is in there and the debugger can now log out the whole model.

Might be released later today or tomorrow :-)

**Comment by gcanti** [comment]
> But type checking is also important, so I want to make it supereasy to start getting into type checking

You are right, introducing developers gradually to type checking is definitely the most important thing. Looking forward to your next release :)

**Comment by christianalfoni** [comment]
But I will use tcomb in the documentation examles ;-)

**Comment by christianalfoni** [comment]
Okay, new release is out. Also two new videos: http://christianalfoni.com/cerebral/ :-)
