### ISSUE TITLE
Using Cerebral with Falcor

### ISSUE THREAD

**Issue by overture8** [christianalfoni/cerebral#76]
I'm curious if Cerebral and Netflix's Falcor make sense together? and if so, what approach should I take to using a Falcor model? I see [here](https://github.com/christianalfoni/cerebral#how-to-create-a-custom-cerebral-model-package) that Cerebral provides a way to create a custom model - does a custom Falcor model for Cerebral exist?

Thanks!

**Comment by christianalfoni** [comment]
Hi @overture8!

I am glad you brought this up because, YES, I have been thinking about this :-)

There are two ways to look at Falcor:

1. It is a model layer (which it presents itself to be)
2. It is a very intelligent ajax library with caching (Which in my opinion, it actually is)

The reason I state this is because Falcor can only handle state sent back and forth from your server. It is not designed to keep all your application state. With that in mind Falcor in a Cerebral sense would be a service you use inside your actions, like any other ajax library. And this is where I think Falcor is doing it right, compared to Relay. It does not require you to split your server state and client state with two completely different ways of handling them.

So an example would be:

```js
function getUsers (input, state, output) {
  input.utils.falcor('requeststring').then(output.success);
}
```
And with next version:
```js
function getUsers (input, state, output, {falcor}) {
  falcor('requeststring').then(output.success);
}
```
The next action in the chain would now set the result inside you model layer, it being immutable store, baobab etc.

So you would treat Falcor as just a really smart ajax library that will cache data for optimization reasons, but you decide exactly what to do with that that fits in with the rest of your state.

Also now the data from Falcor will become truly immutable, which is really important :-)

**Comment by christianalfoni** [comment]
I want to test this out, but do not have time for it yet. Please let me know if you try out my theory here and let me know how it went :-)

**Comment by overture8** [comment]
That makes sense! I think I was getting confused because I was treating the Falcor model as the 'model layer' rather than a smart ajax library, as you say.

I'm going to give this a go!

Thanks.

**Comment by overture8** [comment]
Here's a quick example I knocked together. Pretty simple at the minute - but seems to work ok.

https://github.com/overture8/cerebral-react-falcor-example

**Comment by larryhengl** [comment]
:+1: 
I'm very keenly interested in this topic too.  I've got a project on the horizon that could utilize both tech.
Thanks for initiating it and sharing code, much appreciated!

**Comment by christianalfoni** [comment]
Great @overture8! I checked the example, exactly how I imagined it. Awesome stuff :-)

@larryhengl Please share any experience you have with this, as it is extremely interesting ;-)

**Comment by christianalfoni** [comment]
Just closing this, create a new issue if there are any demos on this :-)
