### ISSUE TITLE
Debugger time adds promise execution time as well

### ISSUE THREAD

**Issue by ksmth** [christianalfoni/cerebral#8]
When I watched one of your tutorials on YouTube, I think I noticed that the debugger added the execution time of promises as well. The way I understood the purpose of the shown value was, that it is used to determine, whether your app is fast enough.

Is it still accurate, when the promises are included?

**Comment by christianalfoni** [comment]
Actually it does not compute the complete signal, but each action is computed. But if an action is async it does not really matter to compute the next actions because now you are running on a new animation frame again. BTW, note to self. After async action it does not wait for next animation frame, which it should. 

Anyways, I am not quite sure how to display a duration of a signal when parts of it is async. Maybe show duration on each action instead and just the accumulated result at the top?

**Comment by ksmth** [comment]
Maybe you visualize which actions took place in what animation frame an sum that up?

```
+------------------------------------+
| app mounted (34ms)                 | <--- total
|+----------------------------------+|
|| 12ms                             || <--- everything up to the next async
|| - 1. setLoadingProjects -        ||
|+----------------------------------+|
|+----------------------------------+|
|| 26ms                             || <--- next group
|| - 2. getProjects (async) -       ||
|| - 3. setProjects -               ||
|| - 4. setProjectRows -            ||
|+----------------------------------+|
+------------------------------------+
```

**Comment by christianalfoni** [comment]
Yeah, that would look awesome, have to wait until I get next release out first though. But will work on it next. Great suggestion, thanks!

**Comment by christianalfoni** [comment]
Want to get a new release out before going into this stuff. It required quite a bit of work and there are more urgent matters to attend, though it will be implemented later :-)

**Comment by christianalfoni** [comment]
Duration is now fixed
