### ISSUE TITLE
parrallel async action's outputs processed only after latest action output

### ISSUE THREAD

**Issue by Guria** [christianalfoni/cerebral#88]
```js
signal('testParallelAsyncOutput',
    [
        ...timeout(5000, [() => { console.log('5000 timeout') }]),
        ...timer.start('pageOpened', 500, [() => { console.log('500 timeout from timer')}])
    ],
    () => { console.log('sync action after async') }
);
```
You will get output from all actions after 5000ms in one moment:
```
> controller.signal.testParallelAsyncOutput()
 500 timeout from timer
 5000 timeout
 sync action after async
```

**Comment by markuplab** [comment]
Yes, because async actions wrapped in Promise.all
https://github.com/christianalfoni/cerebral/blob/master/src/CreateSignalFactory.js#L102

**Comment by Guria** [comment]
It is expected that action defined after array with async actions runs after all of actions defined in it.
But current behaiviour makes breakes some use cases defined in `cerebral-addons`

**Comment by Guria** [comment]
See [example](https://gitter.im/christianalfoni/cerebral?at=55e810a8faa620f25267d61c) from @garth in gitter:
```js
// delayed isLoading, only toggles when async is slow
signal('pageOpened',
  [
    getDataFromServer,  {
      success: [ timer.cancel('pageOpened') ],
      error: [ timer.cancel('pageOpened') ]
    },
    ...timer.start('pageOpened', 500, [ set('isLoading', true) ])
  ],
  set('isLoading', false)
);
```
and https://github.com/christianalfoni/cerebral-addons

**Comment by christianalfoni** [comment]
@Guria ,

Ah, yes, you make a good point there. Hm, maybe this should be refactored then. Allow async actions to resolve when done, but not continue chain until all of them are done?

**Comment by Guria** [comment]
Action right after array should be called only when all parallel pathes in array were evaluated.

**Comment by christianalfoni** [comment]
Jup, exactly, I am reviewing this change now :-)

**Comment by garth** [comment]
@Guria I don't think that this issue breaks the example shown on cerebral addons. That sample is based on code I have running in a real app that works. However, I did expect that my delayed loading sample would work, so perhaps each promise in the the Promise.all needs wrap the entire parallel chain, not just the initial async action.

**Comment by christianalfoni** [comment]
Hm, I think we might get into some issues.

```js
signal('something',
  [
    async1, {
      success: [
        [async3],
        sync1
      ]
    },
    async2, {
      success: [
        [async4],
        sync2
      ]
    }
  ]
);
```

Since the debugger shows everything "in order" you could easily get confused where one async action is running, but outputs from other async actions are now displayed next. Basically, things will not run in order and that is confusing :-)

I think the signal storage and rerun has to be redefined. Now it collects data as the signal is running, but it should probably create the signal definition first, display it in the debugger and then "fill in" the data as the signal runs. That way you debug the signal as it is actually defined, and it will look the same every time, no matter what finishes first.

This requires a lot of thought though, but I think it will be an excellent feature. So imagine that the debugger displays the signal much like you define it in the code, like a sort "tree structure". As the signal runs you will see loaders on async actions, what outputs that activate etc. You can also collapse/expand paths.

Think I will make a mockup of this, but yeah... this will require quite a bit of work. But it is absolutely doable! Actually, I got the next weekend all to myself, I bet I could finish it during that weekend. It would be a really great update I think :-)

**Comment by Guria** [comment]
Great. I had some simiral thoughts that debugger could show more info about how signals were defined.

**Comment by christianalfoni** [comment]
Okay, this stuff is in now :-)
